// Generated by wst
// Requires in Cargo.toml: serde = { version = "1", features = ["derive"] }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum Priority {
    Low,
    Medium,
    High,
    #[deprecated]
    Critical,
    #[deprecated]
    Blocked,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum Payload {
    Text(String),
    Count(i32),
    Data(Vec<String>),
    #[deprecated]
    Legacy(String),
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Record {
    pub id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ref_code: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<u64>,
    pub score: Option<f64>,
    pub active: bool,
    pub label: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lookup: Option<std::collections::HashMap<String, String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flags: Option<Vec<bool>>,
    pub priority: Priority,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<Payload>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RecordSummary {
    pub id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ref_code: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<u64>,
    pub score: Option<f64>,
    pub active: bool,
    pub label: String,
    pub priority: Priority,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ExtendedRecord {
    pub id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ref_code: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<u64>,
    pub score: Option<f64>,
    pub active: bool,
    pub label: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lookup: Option<std::collections::HashMap<String, String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flags: Option<Vec<bool>>,
    pub priority: Priority,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<Payload>,
    pub created_by: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum ApiError {
    NotFound,
    Forbidden,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct InternalAudit {
    pub checksum: String,
    pub processed: bool,
}

pub const DEFAULT_ERROR: ApiError = ApiError::NotFound;

pub static DEFAULT_RECORD: std::sync::LazyLock<Record> = std::sync::LazyLock::new(|| Record {
    id: 1,
    score: 0,
    active: true,
    label: "default".to_string(),
    priority: Priority::Low,
    ref_code: None,
    quantity: None,
    note: None,
    lookup: None,
    flags: None,
    payload: None,
});

