use super::compile;
use crate::ast::File;

fn parse(src: &str) -> File {
    let mut lex = crate::lexer::Lexer::new(src);
    let tokens = lex.tokenize().unwrap();
    crate::parser::Parser::new(tokens).parse_file().unwrap()
}

fn rs(src: &str) -> String {
    compile(&parse(src), std::path::Path::new(".")).unwrap()
}

#[test]
fn header_comment() {
    let out = rs("");
    assert!(out.starts_with("// Generated by wst"));
}

#[test]
fn header_cargo_line() {
    let out = rs("");
    assert!(out.contains("serde = { version = \"1\""));
}

#[test]
fn enum_derives() {
    let out = rs("enum Dir { North };");
    assert!(out.contains("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]"));
}

#[test]
fn enum_basic() {
    let out = rs("enum Direction { North, South };");
    assert!(out.contains("pub enum Direction {"));
    assert!(out.contains("    North,"));
    assert!(out.contains("    South,"));
}

#[test]
fn enum_deprecated_case() {
    let out = rs("enum Dir { North #deprecated };");
    assert!(out.contains("    #[deprecated]\n    North,"));
}

#[test]
fn enum_banned_case() {
    let out = rs("enum Dir { North #banned };");
    assert!(out.contains("    #[deprecated]\n    North,"));
}

#[test]
fn variant_basic() {
    let out = rs("variant Location { Addr = string, Coords = Coords };");
    assert!(out.contains("pub enum Location {"));
}

#[test]
fn variant_case_string() {
    let out = rs("variant Location { Address = string };");
    assert!(out.contains("    Address(String),"));
}

#[test]
fn variant_case_named() {
    let out = rs("variant Location { Coordinates = Coords };");
    assert!(out.contains("    Coordinates(Coords),"));
}

#[test]
fn struct_derives() {
    let out = rs("struct Foo { x = string };");
    assert!(out.contains("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]"));
}

#[test]
fn struct_basic() {
    let out = rs("struct Person { name = string };");
    assert!(out.contains("pub struct Person {"));
}

#[test]
fn struct_optional_field() {
    let out = rs("struct Foo { x = string };");
    assert!(out.contains("    pub x: Option<String>,"));
    assert!(out.contains("#[serde(skip_serializing_if = \"Option::is_none\")]"));
}

#[test]
fn struct_required_field() {
    let out = rs("struct Foo { x = string #required };");
    assert!(out.contains("    pub x: String,"));
    assert!(!out.contains("Option<String>"));
}

#[test]
fn struct_required_no_skip() {
    let out = rs("struct Foo { x = string #required };");
    assert!(!out.contains("skip_serializing_if"));
}

#[test]
fn struct_deprecated_field() {
    let out = rs("struct Foo { x = string #deprecated };");
    assert!(out.contains("#[deprecated]"));
}

#[test]
fn struct_banned_field() {
    let out = rs("struct Foo { x = string #banned };");
    assert!(out.contains("#[deprecated]"));
}

#[test]
fn primitive_int64() {
    let out = rs("struct Foo { x = int64 #required };");
    assert!(out.contains("pub x: i64,"));
}

#[test]
fn primitive_uin64() {
    let out = rs("struct Foo { x = uin64 #required };");
    assert!(out.contains("pub x: u64,"));
}

#[test]
fn primitive_flt64() {
    let out = rs("struct Foo { x = flt64 #required };");
    assert!(out.contains("pub x: f64,"));
}

#[test]
fn primitive_boolean() {
    let out = rs("struct Foo { x = boolean #required };");
    assert!(out.contains("pub x: bool,"));
}

#[test]
fn primitive_string() {
    let out = rs("struct Foo { x = string #required };");
    assert!(out.contains("pub x: String,"));
}

#[test]
fn vec_type_rust() {
    let out = rs("struct Foo { x = vec<string> #required };");
    assert!(out.contains("pub x: Vec<String>,"));
}

#[test]
fn vec_of_named_rust() {
    let out = rs("struct Foo { x = vec<MyType> #required };");
    assert!(out.contains("pub x: Vec<MyType>,"));
}

#[test]
fn map_type_rust() {
    let out = rs("struct Foo { x = map<string, int64> #required };");
    assert!(out.contains("pub x: std::collections::HashMap<String, i64>,"));
}

#[test]
fn named_type_rust() {
    let out = rs("struct Foo { x = MyType #required };");
    assert!(out.contains("pub x: MyType,"));
}

#[test]
fn namespaced_type_rust() {
    let out = rs("struct Foo { x = Ns.MyType #required };");
    assert!(out.contains("pub x: Ns::MyType,"));
}

#[test]
fn named_import_use_statement() {
    let src = "@import ./foo.wst { T };";
    let out = compile(&parse(src), std::path::Path::new(".")).unwrap();
    assert!(out.contains("use super::foo::T;"));
}

#[test]
fn deep_path_import() {
    let src = "@import ./shared/user.wst { User };";
    let out = compile(&parse(src), std::path::Path::new(".")).unwrap();
    assert!(out.contains("use super::shared::user::User;"));
}

#[test]
fn namespace_import_as() {
    let src = "@import ./foo.wst *Ns;";
    let out = compile(&parse(src), std::path::Path::new(".")).unwrap();
    assert!(out.contains("use super::foo as Ns;"));
}

#[test]
fn protocol_is_skipped() {
    let out = rs("protocol P { \"/ep\" <Req, Res> };");
    assert!(!out.contains("protocol"));
    assert!(!out.contains("pub enum P"));
}

#[test]
fn keyword_field_type_escaped() {
    let out = rs("struct Foo { type = string #required };");
    assert!(out.contains("pub r#type: String,"));
}

#[test]
fn keyword_field_fn_escaped() {
    let out = rs("struct Foo { fn = string #required };");
    assert!(out.contains("pub r#fn: String,"));
}

#[test]
fn copy_import_no_use_line() {
    use std::io::Write;
    let dir = tempfile::tempdir().unwrap();
    let wst_path = dir.path().join("dep.wst");
    let mut f = std::fs::File::create(&wst_path).unwrap();
    writeln!(f, "struct Dep {{ x = string }};").unwrap();

    let src = "@import ./dep.wst ^copy { Dep };";
    let file = parse(src);
    let out = compile(&file, dir.path()).unwrap();
    assert!(!out.contains("use "));
    assert!(out.contains("pub struct Dep"));
}

#[test]
fn imports_followed_by_blank_line() {
    let src = "@import ./foo.wst { T };";
    let out = compile(&parse(src), std::path::Path::new(".")).unwrap();
    assert!(out.contains("use super::foo::T;\n\n"));
}
