use anyhow::Result;
use std::path::Path;
use crate::ast::*;
use crate::compiler::{def_name, has_tag, parse_wst_file, resolve_struct_source, resolve_wst_path, strip_wst_ext};

pub fn compile(file: &File, file_dir: &Path) -> Result<String> {
    let mut out = String::new();
    out.push_str("// Generated by wst\n");
    out.push_str("// Requires in Cargo.toml: serde = { version = \"1\", features = [\"derive\"] }\n\n");

    let mut copy_defs: Vec<Definition> = Vec::new();
    let mut has_imports = false;

    for import in &file.imports {
        match &import.kind {
            ImportKind::Named { copy: true, types } => {
                let abs = resolve_wst_path(file_dir, &import.path);
                let imported = parse_wst_file(&abs)?;
                for def in imported.definitions {
                    if types.contains(&def_name(&def).to_string()) {
                        copy_defs.push(def);
                    }
                }
            }
            ImportKind::Named { copy: false, types } => {
                let mod_path = wst_path_to_rust_mod(&import.path);
                for ty in types {
                    out.push_str(&format!("use {}::{};\n", mod_path, ty));
                }
                has_imports = true;
            }
            ImportKind::Namespace { name } => {
                let mod_path = wst_path_to_rust_mod(&import.path);
                out.push_str(&format!("use {} as {};\n", mod_path, name));
                has_imports = true;
            }
        }
    }

    if has_imports {
        out.push('\n');
    }

    let all_defs: Vec<Definition> = copy_defs.iter()
        .chain(file.definitions.iter())
        .cloned()
        .collect();

    for def in &copy_defs {
        emit_definition(&mut out, def, &all_defs);
    }
    for def in &file.definitions {
        emit_definition(&mut out, def, &all_defs);
    }

    Ok(out)
}

fn wst_path_to_rust_mod(path: &str) -> String {
    let s = path.strip_prefix("./").unwrap_or(path);
    let s = strip_wst_ext(s);
    format!("super::{}", s.replace('/', "::"))
}

fn emit_definition(out: &mut String, def: &Definition, all_defs: &[Definition]) {
    match def {
        Definition::Enum(e) => emit_enum(out, e),
        Definition::Variant(v) => emit_variant(out, v),
        Definition::Struct(s) => emit_struct(out, s, all_defs),
        Definition::Protocol(_) => {}
        Definition::Const(c) => emit_const(out, c, all_defs),
    }
}

fn emit_enum(out: &mut String, def: &EnumDef) {
    out.push_str("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\n");
    out.push_str(&format!("pub enum {} {{\n", def.name));
    for case in &def.cases {
        emit_attrs(out, &case.tags, "    ");
        out.push_str(&format!("    {},\n", case.name));
    }
    out.push_str("}\n\n");
}

fn emit_variant(out: &mut String, def: &VariantDef) {
    out.push_str("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\n");
    out.push_str(&format!("pub enum {} {{\n", def.name));
    for case in &def.cases {
        emit_attrs(out, &case.tags, "    ");
        out.push_str(&format!("    {}({}),\n", case.name, type_to_rust(&case.ty)));
    }
    out.push_str("}\n\n");
}

fn emit_struct(out: &mut String, def: &StructDef, all_defs: &[Definition]) {
    out.push_str("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\n");
    out.push_str(&format!("pub struct {} {{\n", def.name));
    for source in &def.copies {
        if let Ok(fields) = resolve_struct_source(source, all_defs) {
            for field in &fields {
                emit_struct_field(out, field);
            }
        }
    }
    for field in &def.fields {
        emit_struct_field(out, field);
    }
    out.push_str("}\n\n");
}

fn expr_has_strings(expr: &crate::ast::Expr) -> bool {
    use crate::ast::Expr;
    match expr {
        Expr::Str { .. } => true,
        Expr::Struct { fields, .. } => fields.iter().any(|f| expr_has_strings(&f.value)),
        _ => false,
    }
}

fn emit_const(out: &mut String, def: &crate::ast::ConstDef, all_defs: &[Definition]) {
    use crate::ast::Expr;
    match &def.value {
        Expr::EnumCase { ty, case } => {
            out.push_str(&format!("pub const {}: {} = {}::{};\n\n", def.name, ty, ty, case));
        }
        Expr::Struct { ty, .. } => {
            let body = expr_to_rust(&def.value, 0, all_defs);
            if expr_has_strings(&def.value) {
                out.push_str(&format!(
                    "pub static {}: std::sync::LazyLock<{}> = std::sync::LazyLock::new(|| {});\n\n",
                    def.name, ty, body
                ));
            } else {
                out.push_str(&format!("pub static {}: {} = {};\n\n", def.name, ty, body));
            }
        }
        Expr::Str { value } => {
            let escaped = value.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n");
            out.push_str(&format!("pub static {}: &str = \"{}\";\n\n", def.name, escaped));
        }
        Expr::Number { value } => {
            let s = if value.fract() == 0.0 { format!("{}", *value as i64) } else { format!("{}", value) };
            out.push_str(&format!("pub const {}: f64 = {};\n\n", def.name, s));
        }
        Expr::Bool { value } => {
            out.push_str(&format!("pub const {}: bool = {};\n\n", def.name, value));
        }
        Expr::Null => {}
    }
}

fn expr_to_rust(expr: &crate::ast::Expr, depth: usize, all_defs: &[Definition]) -> String {
    use crate::ast::Expr;
    let inner_indent = "    ".repeat(depth + 1);
    let close_indent = "    ".repeat(depth);
    match expr {
        Expr::Str { value } => {
            let escaped = value.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n");
            format!("\"{}\".to_string()", escaped)
        }
        Expr::Number { value } => {
            if value.fract() == 0.0 { format!("{}", *value as i64) } else { format!("{}", value) }
        }
        Expr::Bool { value } => value.to_string(),
        Expr::Null => "None".to_string(),
        Expr::EnumCase { ty, case } => format!("{}::{}", ty, case),
        Expr::Struct { ty, fields } => {
            let mut s = format!("{} {{\n", ty);
            // Emit explicitly specified fields
            let specified: std::collections::HashSet<&str> =
                fields.iter().map(|f| field_key(&f.name)).collect();
            for f in fields {
                let key = rust_field_name(field_key(&f.name));
                s.push_str(&format!("{}{}: {},\n", inner_indent, key, expr_to_rust(&f.value, depth + 1, all_defs)));
            }
            // Emit None for unspecified optional fields, resolved from the struct definition
            let source = crate::ast::StructSource::Named { name: ty.clone() };
            if let Ok(all_fields) = resolve_struct_source(&source, all_defs) {
                for sf in &all_fields {
                    let key = field_key(&sf.name);
                    if !specified.contains(key) && !has_tag(&sf.tags, "required") {
                        s.push_str(&format!("{}{}: None,\n", inner_indent, rust_field_name(key)));
                    }
                }
            }
            s.push_str(&format!("{}}}", close_indent));
            s
        }
    }
}

fn emit_struct_field(out: &mut String, field: &StructField) {
    let required = has_tag(&field.tags, "required");
    let nullable = has_tag(&field.tags, "nullable");
    emit_attrs(out, &field.tags, "    ");
    let ty = if required && !nullable {
        type_to_rust(&field.ty)
    } else if required && nullable {
        format!("Option<{}>", type_to_rust(&field.ty))
    } else {
        out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
        format!("Option<{}>", type_to_rust(&field.ty))
    };
    let key = field_key(&field.name);
    out.push_str(&format!("    pub {}: {},\n", rust_field_name(key), ty));
}

/// Returns the output field name: the portion after the last `.` (strips enum qualifier if present).
fn field_key(name: &str) -> &str {
    name.rsplit_once('.').map_or(name, |(_, k)| k)
}

fn emit_attrs(out: &mut String, tags: &[Tag], indent: &str) {
    if has_tag(tags, "deprecated") || has_tag(tags, "banned") {
        out.push_str(&format!("{}#[deprecated]\n", indent));
    }
}

fn rust_field_name(name: &str) -> String {
    match name {
        "type" | "fn" | "let" | "mut" | "pub" | "use" | "mod" | "impl" | "trait"
        | "struct" | "enum" | "for" | "while" | "if" | "else" | "match" | "return"
        | "self" | "where" | "async" | "await" | "move" | "ref" | "in" | "loop" => {
            format!("r#{}", name)
        }
        _ => name.to_string(),
    }
}

fn type_to_rust(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Primitive(p) => primitive_to_rust(p).to_string(),
        TypeRef::Vec(inner) => format!("Vec<{}>", type_to_rust(inner)),
        TypeRef::Map { key, value } => format!(
            "std::collections::HashMap<{}, {}>",
            primitive_to_rust(key),
            type_to_rust(value)
        ),
        TypeRef::Named(name) => name.replace('.', "::"),
    }
}

fn primitive_to_rust(p: &Primitive) -> &str {
    match p {
        Primitive::Int32 => "i32",
        Primitive::Int64 => "i64",
        Primitive::Uin64 => "u64",
        Primitive::Flt64 => "f64",
        Primitive::Boolean => "bool",
        Primitive::Str => "String",
    }
}

#[cfg(test)]
#[path = "rust_tests.rs"]
mod tests;
