// Generated by wst
// Requires in Cargo.toml: serde = { version = "1", features = ["derive"] }

use super::types::Color;
use super::types::Status;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Point {
    pub x: f64,
    pub y: f64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Shape {
    pub x: f64,
    pub y: f64,
    pub color: Color,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    pub label: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ShapePreview {
    pub x: f64,
    pub y: f64,
    pub color: Color,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

