// Generated by wst
// Requires in Cargo.toml: serde = { version = "1", features = ["derive"] }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum Color {
    Red,
    Green,
    Blue,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum Status {
    Active,
    #[deprecated]
    Inactive,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum InternalCode {
    Ok,
    Fail,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Point {
    pub x: f64,
    pub y: f64,
}

